# Generated by Django 5.2.2 on 2025-10-03 18:02

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cukcuapp', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='upload_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(help_text='Upload a book in PDF format', upload_to='books/pdfs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
