# Generated by Django 5.2.2 on 2025-10-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cukcuapp', '0003_book_upload_at_alter_book_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=100)),
                ('achievement', models.CharField(max_length=100)),
                ('recommendation', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='leaderboard/')),
            ],
            options={
                'ordering': ['-period'],
            },
        ),
    ]
