# Generated by Django 5.2.2 on 2025-10-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cukcuapp', '0004_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.CharField(help_text='Path to PDF file', max_length=255),
        ),
        migrations.AlterField(
            model_name='leader',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
