# Generated by Django 5.2.7 on 2025-10-07 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cukcuapp', '0005_alter_book_pdf_file_alter_leader_image_and_more'),
    ]

    operations = [
    ]
