# Generated by Django 5.2.7 on 2025-10-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cukcuapp', '0006_auto_20251007_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(help_text='Upload the book PDF file here.', upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for this leader.', null=True, upload_to='leaders/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for this team member.', null=True, upload_to='team_members/'),
        ),
    ]
