# Generated by Django 5.2.7 on 2025-10-07 22:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cukcuapp', '0007_alter_book_pdf_file_alter_leader_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=cloudinary.models.CloudinaryField(help_text='Upload the book PDF file here.', max_length=255, verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload an image for this leader.', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload an image for this team member.', max_length=255, null=True, verbose_name='image'),
        ),
    ]
