# Generated by Django 5.2.7 on 2025-10-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cukcuapp', '0009_contact_remove_book_pdf_file_book_pdf_public_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order_index', 'name'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AddField(
            model_name='teammember',
            name='order_index',
            field=models.IntegerField(default=99, help_text='Enter a number to define the display order (e.g., Chairman=1, V. Chairman=2, Sec=3).', verbose_name='Display Order'),
        ),
    ]
