# Generated by Django 5.2.7 on 2025-10-08 11:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cukcuapp', '0010_alter_teammember_options_teammember_order_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='upload_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pdf_public_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pdf_url',
        ),
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
