# Generated by Django 5.2.7 on 2025-10-08 13:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cukcuapp', '0011_rename_upload_at_book_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pdf'),
        ),
    ]
