# Generated by Django 5.2.7 on 2025-10-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cukcuapp', '0014_alter_book_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='category',
            field=models.CharField(choices=[('focus', 'Focus members'), ('executive', 'Executive Committee'), ('ministerial', 'Ministerial Leaders')], default='ministerial', max_length=50),
        ),
    ]
