# Generated by Django 5.2.7 on 2025-10-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cukcuapp', '0016_leader_created_at_leader_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
