# Generated by Django 5.2.7 on 2025-10-11 20:42

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cukcuapp', '0017_alter_leader_created_at_alter_teammember_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Upload an image for this team member.', max_length=255, null=True, verbose_name='image')),
                ('category', models.CharField(default='executive', max_length=50)),
                ('order_index', models.IntegerField(default=99, help_text='Enter a number to define the display order (e.g., Chairman=1, V. Chairman=2, Sec=3).', verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order_index', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='leader',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='updated_at',
        ),
    ]
